GO

DECLARE @receiverId UNIQUEIDENTIFIER = N'287E123F-6DC6-4EAB-8F95-14E42B25F1D6'

IF NOT EXISTS(SELECT 1 FROM adm.GlobalConfig WHERE [Key] = N'SVC_RUNCONSOLE')
BEGIN
	INSERT INTO adm.GlobalConfig([Key], [Value])
	VALUES(N'SVC_RUNCONSOLE', N'False')
END

IF NOT EXISTS(SELECT 1 FROM adm.GlobalConfig WHERE [Key] = N'SVC_INSTANCE_ID')
BEGIN
	INSERT INTO adm.GlobalConfig([Key], [Value])
	VALUES(N'SVC_INSTANCE_ID', @receiverId)
END
