GO
DELETE [BIDoc].[SourceDataTypes]
DELETE [BIDoc].[DataTypes]

INSERT INTO BIDoc.DataTypes
(
	[DataTypeName]
)
VALUES (N'String'),
(N'Integer'),
(N'Boolean'),
(N'Character'),
(N'Date'),
(N'Floating-point number'),
(N'Fixed-point number'),
(N'Unknown'),
(N'Image'),
(N'Binary'),
(N'Text');

INSERT INTO [BIDoc].[SourceDataTypes]
(
	[SourceName],
	[SourceDataTypeName],
	[DataTypeId]
)
VALUES ('MS SQL', 'None', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Unknown')),
('MS SQL', 'BigInt', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Integer')),
('MS SQL', 'Binary', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Binary')),
('MS SQL', 'Bit', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Integer')),
('MS SQL', 'Char', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Character')),
('MS SQL', 'DateTime', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Date')),
('MS SQL', 'Decimal', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Fixed-point number')),
('MS SQL', 'Float', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Floating-point number')),
('MS SQL', 'Image', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Image')),
('MS SQL', 'Int', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Integer')),
('MS SQL', 'Money', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Fixed-point number')),
('MS SQL', 'Nchar', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Character')),
('MS SQL', 'Ntext', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'String')),
('MS SQL', 'NVarChar', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Character')),
('MS SQL', 'NVarCharMax', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Text')),
('MS SQL', 'Real', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Floating-point number')),
('MS SQL', 'SmallDateTime', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Date')),
('MS SQL', 'SmallInt', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Integer')),
('MS SQL', 'SmallMoney', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Fixed-point number')),
('MS SQL', 'Text', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Text')),
('MS SQL', 'Timestamp', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Date')),
('MS SQL', 'TinyInt', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Integer')),
('MS SQL', 'UniqueIdentifier', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Integer')),
('MS SQL', 'UserDefinedDataType', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Unknown')),
('MS SQL', 'UserDefinedType', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Unknown')),
('MS SQL', 'VarBinary', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Binary')),
('MS SQL', 'VarBinaryMax', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Binary')),
('MS SQL', 'VarChar', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'String')),
('MS SQL', 'VarCharMax', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Text')),
('MS SQL', 'Variant', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Unknown')),
('MS SQL', 'Xml', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Unknown')),
('MS SQL', 'SysName', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'String')),
('MS SQL', 'Numeric', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Fixed-point number')),
('MS SQL', 'Date', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Date')),
('MS SQL', 'Time', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Date')),
('MS SQL', 'DateTimeOffset', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Date')),
('MS SQL', 'DateTime2 ', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Date')),
('MS SQL', 'UserDefinedTableType', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Unknown')),
('MS SQL', 'HierarchyId', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Integer')),
('MS SQL', 'Geometry', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Unknown')),
('MS SQL', 'Geography', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Unknown')),
('SSIS', 'DT_BOOL', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Boolean')),
('SSIS', 'DT_BYTES', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Binary')),
('SSIS', 'DT_CY', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Integer')),
('SSIS', 'DT_DATE', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Date')),
('SSIS', 'DT_DBDATE', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Date')),
('SSIS', 'DT_DBTIME', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Date')),
('SSIS', 'DT_DBTIME2', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Date')),
('SSIS', 'DT_DBTIMESTAMP', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Date')),
('SSIS', 'DT_DBTIMESTAMP2', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Date')),
('SSIS', 'DT_DBTIMESTAMPOFFSET', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Date')),
('SSIS', 'DT_DECIMAL', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Fixed-point number')),
('SSIS', 'DT_FILETIME', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Date')),
('SSIS', 'DT_GUID', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Integer')),
('SSIS', 'DT_I1', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Integer')),
('SSIS', 'DT_I2', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Integer')),
('SSIS', 'DT_I4', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Integer')),
('SSIS', 'DT_I8', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Integer')),
('SSIS', 'DT_NUMERIC', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Fixed-point number')),
('SSIS', 'DT_R4', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Floating-point number')),
('SSIS', 'DT_R8', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Floating-point number')),
('SSIS', 'DT_STR', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'String')),
('SSIS', 'DT_UI1', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Integer')),
('SSIS', 'DT_UI2', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Integer')),
('SSIS', 'DT_UI4', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Integer')),
('SSIS', 'DT_UI8', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Integer')),
('SSIS', 'DT_WSTR', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'String')),
('SSIS', 'DT_IMAGE', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Image')),
('SSIS', 'DT_NTEXT', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Text')),
('SSIS', 'DT_TEXT', (SELECT DataTypesId FROM [BIDoc].[DataTypes] WHERE DataTypeName = 'Text'));