TRUNCATE TABLE bidoc.modelelementtypedescriptions


INSERT INTO BIDoc.ModelElementTypeDescriptions(ElementType, TypeDescription)
VALUES
(N'CD.DLS.Model.Mssql.Db.ColumnElement', N'SQL Column'),
(N'CD.DLS.Model.Mssql.Db.DatabaseElement', N'SQL Database'),
(N'CD.DLS.Model.Mssql.Db.DeclareVariableElement', N'SQL Variable'),
(N'CD.DLS.Model.Mssql.Db.ForeignKeyElement', N'Foreign Key'),
(N'CD.DLS.Model.Mssql.Db.ProcedureElement', N'Stored Procedure'),
(N'CD.DLS.Model.Mssql.Db.ScalarUdfElement', N'SQL Scalar Function'),
(N'CD.DLS.Model.Mssql.Db.ServerElement', N'SQL Server Instance'),
(N'CD.DLS.Model.Mssql.Db.SchemaElement', N'SQL Schema'),
(N'CD.DLS.Model.Mssql.Db.SchemaTableElement', N'SQL Table'),
(N'CD.DLS.Model.Mssql.Db.SqlDmlSourceElement', N'SQL DML Source'),
(N'CD.DLS.Model.Mssql.Db.SqlDmlTargetReferenceElement', N'SQL DML Target Reference'),
(N'CD.DLS.Model.Mssql.Db.SqlScriptElement', N'SQL Script'),
(N'CD.DLS.Model.Mssql.Db.SqlScriptResultElement', N'SQL Script Result'),
(N'CD.DLS.Model.Mssql.Db.SqlScriptResultColumnElement', N'SQL Script Result Column'),
(N'CD.DLS.Model.Mssql.Db.TableUdfElement', N'SQL Table Function'),
(N'CD.DLS.Model.Mssql.Db.ViewElement', N'SQL View'),
(N'CD.DLS.Model.Mssql.Db.UserDefinedTableTypeElement', N'User-Defined Table Type'),
(N'CD.DLS.Model.Mssql.SolutionModelElement', N'Framework Project'),
(N'CD.DLS.Model.Mssql.Ssas.CubeCalculatedMeasureElement', N'Calculated Cube Measure'),
(N'CD.DLS.Model.Mssql.Ssas.ReportCalculatedMeasureElement', N'Calculated Report Measure'),
(N'CD.DLS.Model.Mssql.Ssas.CubeDimensionElement', N'Cube Dimension'),
(N'CD.DLS.Model.Mssql.Ssas.CubeElement', N'SSAS Cube'),
(N'CD.DLS.Model.Mssql.Ssas.SsasMultidimensionalDatabaseElement', N'SSAS Database'),
(N'CD.DLS.Model.Mssql.Ssas.DatasourceViewColumnElement', N'DSV Column'),
(N'CD.DLS.Model.Mssql.Ssas.DatasourceViewElement', N'Datasource View'),
(N'CD.DLS.Model.Mssql.Ssas.DatasourceViewTableElement', N'DSV Table'),
(N'CD.DLS.Model.Mssql.Ssas.DegenerateMeasureGroupDimensionElement', N'Degenerate Measure Group Dimension'),
(N'CD.DLS.Model.Mssql.Ssas.DimensionAttributeElement', N'Dimension Attribute'),
(N'CD.DLS.Model.Mssql.Ssas.DimensionElement', N'SSAS Dimension'),
(N'CD.DLS.Model.Mssql.Ssas.DsvTableBoundPartitionElement', N'DSV Table Partition'),
(N'CD.DLS.Model.Mssql.Ssas.HierarchyElement', N'Dimension Hierarchy'),
(N'CD.DLS.Model.Mssql.Ssas.HierarchyLevelElement', N'Dimension Hierarchy Level'),
(N'CD.DLS.Model.Mssql.Ssas.KeyColumnElement', N'SSAS Dimension Key'),
(N'CD.DLS.Model.Mssql.Ssas.ManyToManyMeasureGroupDimensionElement', N'M:N Measure Group Dimension'),
(N'CD.DLS.Model.Mssql.Ssas.MdxFragmentElement', N'MDX Fragment'),
(N'CD.DLS.Model.Mssql.Ssas.MdxScriptElement', N'Calculations (MDX)'),
(N'CD.DLS.Model.Mssql.Ssas.MdxStatementElement', N'MDX Statement'),
(N'CD.DLS.Model.Mssql.Ssas.MeasureGroupDimensionColumnBindingElement', N'Measure Group Dimension Binding'),
(N'CD.DLS.Model.Mssql.Ssas.MeasureGroupElement', N'Measure Group'),
(N'CD.DLS.Model.Mssql.Ssas.NameColumnElement', N'Dimension Attribute Name Column'),
(N'CD.DLS.Model.Mssql.Ssas.PartitionColumnElement', N'SSAS Partition Column'),
(N'CD.DLS.Model.Mssql.Ssas.PhysicalMeasureElement', N'Cube Measure'),
(N'CD.DLS.Model.Mssql.Ssas.PhysicalMeasurePartitionSourceElement', N'SSAS Measure Group Partition Source'),
(N'CD.DLS.Model.Mssql.Ssas.QueryBoundPartitionElement', N'SSAS Query-Bound Partition'),
(N'CD.DLS.Model.Mssql.Ssas.RegularMeasureGroupDimensionElement', N'Regular Measure Group Dimension'),
(N'CD.DLS.Model.Mssql.Ssas.RelatedAttributeElement', N'SSAS Related Attribute'),
(N'CD.DLS.Model.Mssql.Ssas.ServerElement', N'SSAS Server Instance'),
(N'CD.DLS.Model.Mssql.Ssis.CatalogElement', N'SSIS Catalog'),
(N'CD.DLS.Model.Mssql.Ssis.ConnectionManagerElement', N'SSIS Connection Manager'),
(N'CD.DLS.Model.Mssql.Ssis.ContainerElement', N'SSIS Container'),
(N'CD.DLS.Model.Mssql.Ssis.DfColumnElement', N'Dataflow Column'),
(N'CD.DLS.Model.Mssql.Ssis.DfComponentElement', N'Dataflow Component'),
(N'CD.DLS.Model.Mssql.Ssis.DfDataConversionElement', N'Data Conversion Component'),
(N'CD.DLS.Model.Mssql.Ssis.DfDestinationElement', N'Dataflow Destination Component'),
(N'CD.DLS.Model.Mssql.Ssis.DfInnerElement', N'SSIS Dataflow Element'),
(N'CD.DLS.Model.Mssql.Ssis.DfInputElement', N'SSIS Dataflow Input'),
(N'CD.DLS.Model.Mssql.Ssis.DfLookupColumnElement', N'SSIS Lookup Column'),
(N'CD.DLS.Model.Mssql.Ssis.DfLookupElement', N'SSIS Lookup'),
(N'CD.DLS.Model.Mssql.Ssis.DfOutputElement', N'SSIS Dataflow Output'),
(N'CD.DLS.Model.Mssql.Ssis.DfPathElement', N'SSIS Dataflow Path'),
(N'CD.DLS.Model.Mssql.Ssis.DfSourceElement', N'SSIS Dataflow Source'),
(N'CD.DLS.Model.Mssql.Ssis.DfTaskElement', N'SSIS Dataflow Task'),
(N'CD.DLS.Model.Mssql.Ssis.ExecutePackageParameterAssignmentElement', N'Execute Package Parameter Assignment'),
(N'CD.DLS.Model.Mssql.Ssis.ExecutePackageTaskElement', N'Execute Package Task'),
(N'CD.DLS.Model.Mssql.Ssis.ExpressionTaskElement', N'Expression Task'),
(N'CD.DLS.Model.Mssql.Ssis.FolderElement', N'SSIS Folder'),
(N'CD.DLS.Model.Mssql.Ssis.PackageElement', N'SSIS Package'),
(N'CD.DLS.Model.Mssql.Ssis.PackageParameterElement', N'SSIS Package Parameter'),
(N'CD.DLS.Model.Mssql.Ssis.PrecedenceConstraintElement', N'Precedence Constraint'),
(N'CD.DLS.Model.Mssql.Ssis.ProjectElement', N'SSIS Project'),
(N'CD.DLS.Model.Mssql.Ssis.ProjectParameterElement', N'Project Parameter'),
(N'CD.DLS.Model.Mssql.Ssis.ServerElement', N'SSIS Server Instance'),
(N'CD.DLS.Model.Mssql.Ssis.SqlTaskElement', N'SSIS SQL Task'),
(N'CD.DLS.Model.Mssql.Ssis.SsisExpressionFragmentElement', N'SSIS Expression Fragment'),
(N'CD.DLS.Model.Mssql.Ssis.SystemVariableElement', N'SSIS System Variable'),
(N'CD.DLS.Model.Mssql.Ssis.TaskElement', N'SSIS Task'),
(N'CD.DLS.Model.Mssql.Ssis.VariableElement', N'SSIS Variable'),
(N'CD.DLS.Model.Mssql.Ssrs.CellElement', N'SSRS Cell'),
(N'CD.DLS.Model.Mssql.Ssrs.DataSetFieldElement', N'SSRS Dataset Field'),
(N'CD.DLS.Model.Mssql.Ssrs.FolderElement', N'SSRS Folder'),
(N'CD.DLS.Model.Mssql.Ssrs.GaugePanelElement', N'SSRS Gauge Panel'),
(N'CD.DLS.Model.Mssql.Ssrs.HierarchyGroupElement', N'SSRS Hierarchy Group'),
(N'CD.DLS.Model.Mssql.Ssrs.HierarchyMemberElement', N'SSRS Hierarchy Member'),
(N'CD.DLS.Model.Mssql.Ssrs.ChartDataElement', N'SSRS Chart Data'),
(N'CD.DLS.Model.Mssql.Ssrs.ChartDataPointElement', N'Chart Data Point'),
(N'CD.DLS.Model.Mssql.Ssrs.ChartElement', N'SSRS Chart'),
(N'CD.DLS.Model.Mssql.Ssrs.ChartSeriesElement', N'Chart Series'),
(N'CD.DLS.Model.Mssql.Ssrs.IndicatorGaugeElement', N'Indicator Gauge'),
(N'CD.DLS.Model.Mssql.Ssrs.ParameterValueElement', N'SSRS Parameter Value'),
(N'CD.DLS.Model.Mssql.Ssrs.QueryParameterElement', N'SSRS Query Parameter'),
(N'CD.DLS.Model.Mssql.Ssrs.RectangleElement', N'SSRS Rectangle'),
(N'CD.DLS.Model.Mssql.Ssrs.ReportDataSetElement', N'Report Dataset'),
(N'CD.DLS.Model.Mssql.Ssrs.ReportDataSourceElement', N'Report Data Source'),
(N'CD.DLS.Model.Mssql.Ssrs.ReportElement', N'SSRS Report'),
(N'CD.DLS.Model.Mssql.Ssrs.ReportParameterDefaultValuesDataSetElement', N'Report Parameter Default Values Dataset'),
(N'CD.DLS.Model.Mssql.Ssrs.ReportParameterDefaultValuesStaticElement', N'Report Parameter Default Values'),
(N'CD.DLS.Model.Mssql.Ssrs.ReportParameterElement', N'Report Parameter'),
(N'CD.DLS.Model.Mssql.Ssrs.ReportParameterValidValuesDataSetElement', N'Report Parameter Valid Values Dataset'),
(N'CD.DLS.Model.Mssql.Ssrs.ReportParameterValidValuesStaticElement', N'Report Parameter Valid Values'),
(N'CD.DLS.Model.Mssql.Ssrs.ReportSectionBodyElement', N'Report Section Body'),
(N'CD.DLS.Model.Mssql.Ssrs.ReportSectionElement', N'Report Section'),
(N'CD.DLS.Model.Mssql.Ssrs.ServerElement', N'SSRS Instance'),
(N'CD.DLS.Model.Mssql.Ssrs.SharedDataSetElement', N'SSRS Shared Dataset'),
(N'CD.DLS.Model.Mssql.Ssrs.SharedDataSourceElement', N'SSRS Shared Dtasource'),
(N'CD.DLS.Model.Mssql.Ssrs.SsrsExpressionElement', N'SSRS Expression'),
(N'CD.DLS.Model.Mssql.Ssrs.SsrsExpressionFragmentElement', N'SSRS Expression Fragment'),
(N'CD.DLS.Model.Mssql.Ssrs.TablixColumnHierarchyElement', N'Tablix Column Hierarchy'),
(N'CD.DLS.Model.Mssql.Ssrs.TablixElement', N'Tablix'),
(N'CD.DLS.Model.Mssql.Ssrs.TablixRowElement', N'Tablix Row'),
(N'CD.DLS.Model.Mssql.Ssrs.TablixRowHierarchyElement', N'Tablix Row Hierarchy'),
(N'CD.DLS.Model.Mssql.Ssrs.TextBoxElement', N'SSRS Textbox'),
(N'CD.DLS.Model.Mssql.Db.SqlNAryOperationOutputColumnElement', N'Set Operation Output Column'),
(N'CD.DLS.Model.Mssql.Db.SqlNAryOperationOperandColumnElement', N'Set Operation Operand Column'),
(N'CD.DLS.Model.Mssql.Ssis.DbConnectionManagerElement', N'Connection Manager'),
(N'CD.DLS.Model.Mssql.Db.ForeignDbTableElement', N'SQL Table'),
(N'CD.DLS.Model.Mssql.Db.ForeignProviderSqlScriptElement', N'Unknown DB Connection Provider'),
(N'CD.DLS.Model.Mssql.Ssas.ReferencedMeasureGroupDimensionElement', N'Referenced Measure Group Dimension'),
(N'CD.DLS.Model.Mssql.Ssas.TableBoundPartitionElement', N'Table-Bound Partition'),
(N'CD.DLS.Model.Mssql.Ssas.ValueColumnElement', N'SSAS Dimension Value Column'),
(N'CD.DLS.Model.Mssql.Ssis.DfLookupOutputJoinReferenceElement', N'Lookup Column Reference'),
(N'CD.DLS.Model.Mssql.Ssis.DfUnionAllElement', N'Union All Transformation'),
(N'CD.DLS.Model.Mssql.Ssis.DfUnpivotSourceReferenceElement', N'SSIS Unpivot Source Reference Element'),
(N'CD.DLS.Model.Mssql.Ssis.DfMergeJoinElement', N'SSIS Merge Join'),
(N'CD.DLS.Model.Mssql.Ssas.CustomRollupColumnElement', N'Custom Rollup Column'),
(N'CD.DLS.Model.Mssql.Ssas.CustomRollupPropertiesColumnElement', N'Custom Rollup Proprties'),
(N'CD.DLS.Model.Mssql.Ssas.UnaryOperatorColumnElement', N'SSAS Unary Operator'),
(N'CD.DLS.Model.Mssql.Ssis.DfUnpivotElement', N'Unpivot Component'),
(N'CD.DLS.Model.Mssql.Ssis.FileConnectionManagerElement', N'File Connection Manager'),
(N'CD.DLS.Model.Mssql.Ssis.DfDerivedColumnElement', N'Derived Column Information'),
('CD.DLS.Model.Mssql.Ssis.DfColumnAggregationLinkElement', N'SSIS Aggregation Link'),

(N'CD.DLS.Model.Mssql.Tabular.SsasTabularDatabaseElement', N'Tabular Database'),
(N'CD.DLS.Model.Mssql.Tabular.SsasTabularDataSourceElement', N'Tabular Database Data Source'),
(N'CD.DLS.Model.Mssql.Tabular.SsasTabularTableElement', N'Tabular Database Table'),
(N'CD.DLS.Model.Mssql.Tabular.SsasTabularTableColumnElement', N'Tabular Database Column'),
(N'CD.DLS.Model.Mssql.Tabular.SsasTabularAnnotationElement', N'Tabular Database Annotation'),
(N'CD.DLS.Model.Mssql.Tabular.SsasTabularAttributeHierarchyElement', N'Tabular Attribute Hierarchy'),
(N'CD.DLS.Model.Mssql.Tabular.SsasTabularPartitionElement', N'Tabular Partition'),
(N'CD.DLS.Model.Mssql.Tabular.SsasTabularPartitionColumnElement', N'Tabular Partition Column'),
(N'CD.DLS.Model.Mssql.Tabular.SsasTabularMeasureElement', N'Tabular Measure'),
(N'CD.DLS.Model.Mssql.Tabular.SsasTabularHierarchyElement', N'Tabular Hierarchy'),
(N'CD.DLS.Model.Mssql.Tabular.SsasTabularRelationshipElement', N'Tabular Relationship'),
(N'CD.DLS.Model.Mssql.Tabular.SsasTabularPerspectiveElement', N'Tabular Perspective'),
(N'CD.DLS.Model.Mssql.Tabular.SsasTabularHierarchyLevelElement', N'Tabular Hierarchy Level'),

(N'CD.DLS.Model.Business.Organization.BusinessFolderElement', N'Folder'),
(N'CD.DLS.Model.Business.Organization.BusinessRootElement', N'Business Objects'),
(N'CD.DLS.Model.Business.Excel.PivotTableTemplateElement', N'Pivot Table Template'),
(N'CD.DLS.Model.Business.Excel.PivotTableFieldElement', N'Pivot Table Field'),
(N'CD.DLS.Model.Business.Excel.PivotTableValuesFilterElement', N'Pivot Table Values Filter'),

(N'CD.DLS.Model.Mssql.Ssas.CubeDimensionAttributeElement', N'Cube Dimension Attribute'),
(N'CD.DLS.Model.Mssql.Ssas.CubeDimensionHierarchyElement', N'Cube Dimension Hierarchy'),
(N'CD.DLS.Model.Mssql.Ssas.CubeDimensionHierarchyLevelElement', N'Cube Dimension Hierarchy Level'),

(N'CD.DLS.Model.Mssql.Pbi.TenantElement', N'Power BI Tenant'),
(N'CD.DLS.Model.Mssql.Pbi.ReportElement', N'Power BI Report'),
(N'CD.DLS.Model.Mssql.Pbi.ReportSectionElement', N'Report Page'),
(N'CD.DLS.Model.Mssql.Pbi.VisualElement', N'Power BI Report Visual'),
(N'CD.DLS.Model.Mssql.Pbi.ProjectionElement', N'Power BI Visual Field'),
(N'CD.DLS.Model.Mssql.Pbi.ConnectionElement', N'Data Source'),
(N'CD.DLS.Model.Mssql.Pbi.PbiTableElement', N'Power BI Table'),
(N'CD.DLS.Model.Mssql.Pbi.PbiColumnElement', N'Power BI Table Column'),
(N'CD.DLS.Model.Mssql.Pbi.FilterElement', N'Filter'),

-- DAX general start

('CD.DLS.Model.Mssql.Ssas.UnknownDaxTableFunctionElement', N'DAX Table Function'),
('CD.DLS.Model.Mssql.Ssas.GeneralDaxScalarFunctionElement', N'DAX Scalar Function'),
('CD.DLS.Model.Mssql.Ssas.DaxLocalVariableElement', N'DAX Local Variable'),
('CD.DLS.Model.Mssql.Ssas.DaxLocalMeasureElement', N'DAX Local Measure'),
('CD.DLS.Model.Mssql.Ssas.DaxBinaryScalarOperationElement', N'DAX Binary Scalar Operation'),
('CD.DLS.Model.Mssql.Ssas.DaxUnaryScalarOperationElement', N'DAX Unary Scalar Operation'),
('CD.DLS.Model.Mssql.Ssas.DaxTableOperationElement', N'DAX Table Operation'),
('CD.DLS.Model.Mssql.Ssas.DaxTableOperationOutputColumnElement', N'DAX Table Operation Output Column'),
('CD.DLS.Model.Mssql.Ssas.DaxScalarOperationElement', N'DAX Scalar Operation'),
('CD.DLS.Model.Mssql.Ssas.DaxOperationArgumentElement', N'DAX Operation Argument'),
('CD.DLS.Model.Mssql.Ssas.DaxColumnReferenceElement', N'DAX Column Reference'),
('CD.DLS.Model.Mssql.Ssas.DaxTableReferenceElement', N'DAX Table Reference'),
('CD.DLS.Model.Mssql.Ssas.DaxLiteralElement', N'DAX Literal Value'),
('CD.DLS.Model.Mssql.Ssas.DaxDataFlowLinkElement', N'DAX Data Flow Link'),
('CD.DLS.Model.Mssql.Ssas.DaxScriptElement', N'DAX Script'),
('CD.DLS.Model.Mssql.Ssas.DaxFragmentElement', N'DAX Fragment'),

-- DAX general end

-- DAX functions start

('CD.DLS.Model.Mssql.Ssas.DaxCalendarFunctionElement', N'DaxCalendarFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxCalendarAutoFunctionElement', N'DaxCalendarAutoFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxDateFunctionElement', N'DaxDateFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxDateDiffFunctionElement', N'DaxDateDiffFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxDateValueFunctionElement', N'DaxDateValueFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxDayFunctionElement', N'DaxDayFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxEDateFunctionElement', N'DaxEDateFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxEOMonthFunctionElement', N'DaxEOMonthFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxHourFunctionElement', N'DaxHourFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxMinuteFunctionElement', N'DaxMinuteFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxMonthFunctionElement', N'DaxMonthFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxNowFunctionElement', N'DaxNowFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxSecondFunctionElement', N'DaxSecondFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxTimeFunctionElement', N'DaxTimeFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxTimeValueFunctionElement', N'DaxTimeValueFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxTodayFunctionElement', N'DaxTodayFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxUtcNowFunctionElement', N'DaxUtcNowFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxUtcTodayFunctionElement', N'DaxUtcTodayFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxWeekDayFunctionElement', N'DaxWeekDayFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxWeekNumFunctionElement', N'DaxWeekNumFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxYearFunctionElement', N'DaxYearFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxYearFracFunctionElement', N'DaxYearFracFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxClosingBalanceMonthFunctionElement', N'DaxClosingBalanceMonthFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxClosingBalanceQuarterFunctionElement', N'DaxClosingBalanceQuarterFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxClosingBalanceYearFunctionElement', N'DaxClosingBalanceYearFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxDateAddFunctionElement', N'DaxDateAddFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxDatesBetweenFunctionElement', N'DaxDatesBetweenFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxDatesInPeriodFunctionElement', N'DaxDatesInPeriodFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxDatesMtdFunctionElement', N'DaxDatesMtdFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxDatesQtdFunctionElement', N'DaxDatesQtdFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxDatesYtdFunctionElement', N'DaxDatesYtdFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxEndOfMonthFunctionElement', N'DaxEndOfMonthFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxEndOfQuarterFunctionElement', N'DaxEndOfQuarterFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxEndOfYearFunctionElement', N'DaxEndOfYearFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxFirstDateFunctionElement', N'DaxFirstDateFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxFirstNonBlankFunctionElement', N'DaxFirstNonBlankFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxLastDateFunctionElement', N'DaxLastDateFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxLastNonBlankFunctionElement', N'DaxLastNonBlankFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxNextDayFunctionElement', N'DaxNextDayFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxNextMonthFunctionElement', N'DaxNextMonthFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxNextQuarterFunctionElement', N'DaxNextQuarterFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxNextYearFunctionElement', N'DaxNextYearFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxOpeningBalanceMonthFunctionElement', N'DaxOpeningBalanceMonthFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxOpeningBalanceQuarterFunctionElement', N'DaxOpeningBalanceQuarterFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxOpeningBalanceYearFunctionElement', N'DaxOpeningBalanceYearFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxParallelPeriodFunctionElement', N'DaxParallelPeriodFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxPreviousDayFunctionElement', N'DaxPreviousDayFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxPreviousMonthFunctionElement', N'DaxPreviousMonthFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxPreviousQuarterFunctionElement', N'DaxPreviousQuarterFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxPreviousYearFunctionElement', N'DaxPreviousYearFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxSamePeriodLastYearFunctionElement', N'DaxSamePeriodLastYearFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxStartOfMonthFunctionElement', N'DaxStartOfMonthFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxStartOfQuarterFunctionElement', N'DaxStartOfQuarterFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxStartOfYearFunctionElement', N'DaxStartOfYearFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxTotalMtdFunctionElement', N'DaxTotalMtdFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxTotalQtdFunctionElement', N'DaxTotalQtdFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxTotalYtdFunctionElement', N'DaxTotalYtdFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxAddMissingItemsFunctionElement', N'DaxAddMissingItemsFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxAllFunctionElement', N'DaxAllFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxAllExceptFunctionElement', N'DaxAllExceptFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxAllNoBlankRowFunctionElement', N'DaxAllNoBlankRowFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxAllSelectedFunctionElement', N'DaxAllSelectedFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxCalculateFunctionElement', N'DaxCalculateFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxCalculateTableFunctionElement', N'DaxCalculateTableFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxCrossFilterFunctionElement', N'DaxCrossFilterFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxDistinctFunctionElement', N'DaxDistinctFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxEarlierFunctionElement', N'DaxEarlierFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxEarliestFunctionElement', N'DaxEarliestFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxFilterFunctionElement', N'DaxFilterFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxFiltersFunctionElement', N'DaxFiltersFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxHasOneFilterFunctionElement', N'DaxHasOneFilterFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxHasOneValueFunctionElement', N'DaxHasOneValueFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxIsCrossFilteredFunctionElement', N'DaxIsCrossFilteredFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxIsFilteredFunctionElement', N'DaxIsFilteredFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxKeepFiltersFunctionElement', N'DaxKeepFiltersFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxRelatedFunctionElement', N'DaxRelatedFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxRelatedTableFunctionElement', N'DaxRelatedTableFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxSelectedValueFunctionElement', N'DaxSelectedValueFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxSubstituteWithIndexFunctionElement', N'DaxSubstituteWithIndexFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxUseRelationshipFunctionElement', N'DaxUseRelationshipFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxValuesFunctionElement', N'DaxValuesFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxContainsFunctionElement', N'DaxContainsFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxCustomDataFunctionElement', N'DaxCustomDataFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxIsBlankFunctionElement', N'DaxIsBlankFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxIsErrorFunctionElement', N'DaxIsErrorFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxIsEvenFunctionElement', N'DaxIsEvenFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxIsInScopeFunctionElement', N'DaxIsInScopeFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxIsLogicalFunctionElement', N'DaxIsLogicalFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxIsNonTextFunctionElement', N'DaxIsNonTextFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxIsNumberFunctionElement', N'DaxIsNumberFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxIsOddFunctionElement', N'DaxIsOddFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxIsOnOrAfterFunctionElement', N'DaxIsOnOrAfterFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxIsTextFunctionElement', N'DaxIsTextFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxLookupValueFunctionElement', N'DaxLookupValueFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxUserNameFunctionElement', N'DaxUserNameFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxAndFunctionElement', N'DaxAndFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxFalseFunctionElement', N'DaxFalseFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxIfFunctionElement', N'DaxIfFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxIfErrorFunctionElement', N'DaxIfErrorFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxNotFunctionElement', N'DaxNotFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxOrFunctionElement', N'DaxOrFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxSwitchFunctionElement', N'DaxSwitchFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxTrueFunctionElement', N'DaxTrueFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxDataTableFunctionElement', N'DaxDataTableFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxErrorFunctionElement', N'DaxErrorFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxExceptFunctionElement', N'DaxExceptFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxGenerateSeriesFunctionElement', N'DaxGenerateSeriesFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxGroupByFunctionElement', N'DaxGroupByFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxIntersectFunctionElement', N'DaxIntersectFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxIsEmptyFunctionElement', N'DaxIsEmptyFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxNaturalInnerJoinFunctionElement', N'DaxNaturalInnerJoinFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxNaturalLeftOuterJoinFunctionElement', N'DaxNaturalLeftOuterJoinFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxSummarizeColumnsFunctionElement', N'DaxSummarizeColumnsFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxTreatAsFunctionElement', N'DaxTreatAsFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxUnionFunctionElement', N'DaxUnionFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxAddColumnsFunctionElement', N'DaxAddColumnsFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxCrossJoinFunctionElement', N'DaxCrossJoinFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxGenerateFunctionElement', N'DaxGenerateFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxGenerateAllFunctionElement', N'DaxGenerateAllFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxRowFunctionElement', N'DaxRowFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxSampleFunctionElement', N'DaxSampleFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxSelectColumnsFunctionElement', N'DaxSelectColumnsFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxSummarizeFunctionElement', N'DaxSummarizeFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxCountRowsFunctionElement', N'DaxCountRowsFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxCountFunctionElement', N'DaxCountFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxCountaFunctionElement', N'DaxCountaFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxDistinctCountFunctionElement', N'DaxDistinctCountFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxSumFunctionElement', N'DaxSumFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxBlankFunctionElement', N'DaxBlankFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxFormatFunctionElement', N'DaxFormatFunction'),
('CD.DLS.Model.Mssql.Ssas.DaxRightFunctionElement', N'DaxRightFunction'),

-- DAX functions end

-- Power Query general start

('CD.DLS.Model.Mssql.PowerQuery.MFragmentElement', N'PowerQuery Fragment'),
('CD.DLS.Model.Mssql.PowerQuery.PowerQueryElement', N'PowerQuery Operation'),
('CD.DLS.Model.Mssql.PowerQuery.DataFlowLinkElement', N'PowerQuery Data Flow'),
('CD.DLS.Model.Mssql.PowerQuery.LiteralElement', N'PowerQuery Literal'),
('CD.DLS.Model.Mssql.PowerQuery.IdentifierElement', N'PowerQuery Identifier'),
('CD.DLS.Model.Mssql.PowerQuery.RecordItemIdentifierElement', N'PowerQuery Record Item'),
('CD.DLS.Model.Mssql.PowerQuery.VariableReferenceElement', N'PowerQuery Variable Reference'),
('CD.DLS.Model.Mssql.PowerQuery.FormulaStepElement', N'PowerQuery Formula Step'),
('CD.DLS.Model.Mssql.PowerQuery.OperationArgumentElement', N'PowerQuery Operation Argument'),
('CD.DLS.Model.Mssql.PowerQuery.ListElement', N'PowerQuery Literal'),
('CD.DLS.Model.Mssql.PowerQuery.ListIndexElement', N'PowerQuery List Index'),
('CD.DLS.Model.Mssql.PowerQuery.ListAccessElement', N'PowerQuery List Access'),
('CD.DLS.Model.Mssql.PowerQuery.RecordElement', N'PowerQuery  Record'),
('CD.DLS.Model.Mssql.PowerQuery.RecordItemElement', N'PowerQuery Record Item'),
('CD.DLS.Model.Mssql.PowerQuery.OperationElement', N'PowerQuery Operation'),
('CD.DLS.Model.Mssql.PowerQuery.SqlDatabaseOperationElement', N'PowerQuery SQL DB Access'),
('CD.DLS.Model.Mssql.PowerQuery.ScalarOperationElement', N'PowerQuery Scalar Operation'),
('CD.DLS.Model.Mssql.PowerQuery.OperationOutputColumnElement', N'PowerQuery Operation Output Column'),
('CD.DLS.Model.Mssql.PowerQuery.TableRowOperationElement', N'PowerQuery Row Operation'),
('CD.DLS.Model.Mssql.PowerQuery.TableSplitColumnOperationElement', N'PowerQuery Split Column'),
('CD.DLS.Model.Mssql.PowerQuery.TableDuplicateColumnOperationElement', N'PowerQuery Dulicate Column'),
('CD.DLS.Model.Mssql.PowerQuery.TableRemoveColumnsOperationElement', N'PowerQuery Remove Column'),
('CD.DLS.Model.Mssql.PowerQuery.TableSelectColumnsOperationElement', N'PowerQuery Select Columns'),
('CD.DLS.Model.Mssql.PowerQuery.TableRenameColumnsOperationElement', N'PowerQuery Rename Columns'),
('CD.DLS.Model.Mssql.PowerQuery.GeneralOperationElement', N'PowerQuery General Operation')

-- Power Query general end